// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    BACKEND?: string;
    DEFAULT_BACKEND?: string;
    CUSTOM_BACKEND?: string;
    LOCK_BACKEND?: boolean;
    REMOTE_CONFIG?: string;
    CHUNK_COUNT?: string;
    DB?: D1Database;
    /** 短链服务是否启用，由运行时适配层根据仓储可用性注入 */
    SHORT_URL_ENABLED?: boolean;
}
